services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: compass
      POSTGRES_PASSWORD: compass
      POSTGRES_DB: vote_compass
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

  api:
    build: .
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  worker:
    build: .
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: celery -A app.worker.celery_app worker --loglevel=info

volumes:
  db_data:
